### ISSUE TITLE
Бот не забирает всех заложников

### ISSUE THREAD

**Issue by rakakarakaka** [yapb/yapb#606]
Бот на cs_assault взял одного заложника, я на пути случайно стал на одну секунду, он затупил что-то, затем спрыгнул с высоты и пошел по делам... Заложник один и тот не смог за ним пойти стал у окна и все. 

Может быть ботам нужна какая-то дополнительная проверка, что если на карте 4 заложника, а он взял только одного, что бы вернулся за остальными, толку ведь нет от одного заложника...

**Comment by UnrealKaraulov** [comment]
По умолчанию они на cs_assault берут заложников и прыгают в окно, а заложники за ними не прыгают.

**Comment by rakakarakaka** [comment]
бот берет заложников и выпрыгивает в окно, в кс 1.6 заложники тупые и в окно за ботом не прыгают как ни странно

**Comment by rakakarakaka** [comment]
@jeefo может быть можно как-то отключить ботам прыжки в высоту и ползание когда они выводят туповатых заложников из cs 1.6, а так же добавить проверку все ли заложники следуют за ботами?

**Comment by MysticDeathProject** [comment]
приветик а версия yapb последняя эта? [Update continuous](https://github.com/yapb/yapb/releases/tag/continuous) как вариант можешь попробовать поставить ботам игнор спасения заложников или установления бомбы yb_ignore_objectives 1 и играть без спасения заложников, но это проблема в самих заложниках они перестают следовать за ботом и бот их теряет из виду и думает что спасает их, возможное решение еще можно попробовать поставить [RegameDll](https://github.com/s1lentq/ReGameDLL_CS/releases) там вроде были какие то исправления тупости заложникам

**Comment by UnrealKaraulov** [comment]
> приветик а версия yapb последняя эта? [Update continuous](https://github.com/yapb/yapb/releases/tag/continuous) как вариант можешь попробовать поставить ботам игнор спасения заложников или установления бомбы yb_ignore_objectives 1 и играть без спасения заложников, но это проблема в самих заложниках они перестают следовать за ботом и бот их теряет из виду и думает что спасает их, возможное решение еще можно попробовать поставить [RegameDll](https://github.com/s1lentq/ReGameDLL_CS/releases) там вроде были какие то исправления тупости заложникам

я проверял на cs assault, бот берет заложников, и зачем-то выпрыгивает прямо в окно, ну естественно они в окно за ним не могут выпрыгнуть 🤣 🤣 🤣

**Comment by jeefo** [comment]
Что выплевывает ``yb g fileinfo`` ?

**Comment by UnrealKaraulov** [comment]
@jeefo 

анализ до 100% не доходит

```
Rebuilding vistable... 92% done.
Rebuilding vistable... 95% done.
Rebuilding vistable... 98% done.
yb g fileinfo
header:
  magic: 1497452610
  version: 2
  node_count: 911
  compressed_size: 46kB
  uncompressed_size: 195kB
  options: 72
  analyzed: no

extensions:
  author: $_Vladislav
  modified_by:
  bsp_size: 1041700
   ```
   
 Теперь бот вместо того что бы идти к заложникам подходит ко второй камере и начинать палить в нее со всего что только есть пока не закончатся патроны.
 
 
![image](https://github.com/user-attachments/assets/79f5687e-266c-4ea9-bde0-a84c7c3ae814)


Когда убиваю вражеского бота, он берет двух заложников ближних которые, подходит к следующим, не берет их, возвращается на место где стояли первые, тычет носом кудато в стену, и потом уходит.

Прыгать в окно перестали когда берут заложников.
